language: java
jdk:
    - oraclejdk8
    
script: mvn test -f ./previnaApi/pom.xml

sudo: false
install: true

addons:
  sonarcloud:
    organization: "kynake-github"
    token: 
      secure: "GMtSBu8MFyFvZ2mLuxHZ9Q"
